### ISSUE TITLE
Translatable doesn't let you assign per-locale editing rights unless you have called Translatable::set_allowed_locales()

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-translatable#10]
Migrated from http://open.silverstripe.org/ticket/4939

Steps to reproduce:

Set up a translatable site
Ensure that set_allowed_locales isn't set
Log in as admin and create pages in a few languages
Go to the security area, and the permissions tab on a group
We would expect to have the right to assign permission to translate into each of the languages that we specified. However, the language-specific permission checkboxes aren't shown if we omit set_allowed_locales.

We only have the option "Translate into all available languages".

Recommended fix is to update Translatable::providePermissions() to search for all the translations that have been used on SiteTree? pages, if allowed_locales isn't set.

**Comment by robbieaverill** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
