### ISSUE TITLE
radio option with translatable not working

### ISSUE THREAD

**Issue by wakeworks** [silverstripe/silverstripe-translatable#100]
Hi everyone, when I try to add a radio option with translatable installed I receive the following error:
[Error] Uncaught InvalidArgumentException: Invalid locale "en_GB/field/Fields/addoptionfield" /.../translatable/code/model/Translatable.php:311 

I use Silverstripe 3.0.5 with the newest translatable module. 
Thanks for reply - Tommi

**Comment by robbieaverill** [comment]
If this is still affecting you on more recent versions of SilverStripe and translatable, @wakeworks, please feel free to reopen.
