### ISSUE TITLE
current_site_config() and Translatable (disastrous problem)

### ISSUE THREAD

**Issue by Josua2012** [silverstripe/silverstripe-translatable#108]
When modifying SiteConfig fields in the CMS and we do refresh on the web in another tab (Firefox 20.0.1) the results are disastrous for SiteConfig table.
Follow the steps to reproduce the problem:
- Install the latest SilverStripe version 3.1 (28/04/2013) from github
- Install the latest version of Translatable module from github .
- The configuration of mysite/_config.php is:

```
Director::set_environment_type('dev');
// Set the site locale
i18n::set_locale('en_US');
Translatable::set_default_locale('en_US');
Translatable::set_allowed_locales(array(
    'en_US',  // US English
    'es_ES'  // Español
));
```
- Create a new home page for the Spanish language
  ![translatable00](https://f.cloud.github.com/assets/1523607/435732/a46521c2-b000-11e2-8861-8fe91a1dc945.png)
- See the following images:
  ![translatable01](https://f.cloud.github.com/assets/1523607/435733/c499119c-b000-11e2-8216-2c80078d618e.png)
  ![translatable02](https://f.cloud.github.com/assets/1523607/435734/c8e9cc96-b000-11e2-9bc3-46945103375b.png)
  ![translatable03](https://f.cloud.github.com/assets/1523607/435735/cb98cb36-b000-11e2-80d5-8f60e99a2110.png)
  ![translatable04](https://f.cloud.github.com/assets/1523607/435736/ce2bd186-b000-11e2-9bde-2af083c2463d.png)
  ![translatable05](https://f.cloud.github.com/assets/1523607/435737/d1c3a68e-b000-11e2-8bf9-0cd5a22a390a.png)
  ![translatable06](https://f.cloud.github.com/assets/1523607/435738/d4f30138-b000-11e2-9a01-5608388e8848.png)
  ![translatable07](https://f.cloud.github.com/assets/1523607/435739/d77cf6ac-b000-11e2-8c95-7f3ad3755be8.png)
  ![translatable08](https://f.cloud.github.com/assets/1523607/435740/da306988-b000-11e2-9327-0bcafd370be9.png)
  ![translatable09](https://f.cloud.github.com/assets/1523607/435741/dd6e6fb4-b000-11e2-8c7a-a63fc3463f0e.png)

```
    static public function current_site_config() {
        if ($siteConfig = DataObject::get_one('SiteConfig')) return $siteConfig;

        return self::make_site_config();
    }
```

The problem apparently is that DataObject::get_one('SiteConfig') returns no records and therefore runs the line 
return self::make_site_config()

Regards,
Jose A.

**Comment by memdev** [comment]
I had the same problem for some of my sites and finally found a solution.
I made it a SilverStripe module so you can install it via composer.

https://github.com/memdev/siteconfig-translatable-fix

**Comment by tractorcow** [comment]
@memdev is there any chance we could merge this fix into the translatable module?

**Comment by memdev** [comment]
@tractorcow Sure! If not already done, feel free to grab the code and integrate it as needed.

**Comment by robbieaverill** [comment]
@memdev would you be interested in submitting a pull request?

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.

**Comment by xini** [comment]
Just wait long enough and the tickets go away by themselves....
