### ISSUE TITLE
createTranslation() doesn't create new entry in SiteTree_versions

### ISSUE THREAD

**Issue by Josua2012** [silverstripe/silverstripe-translatable#111]
See failing unit test: https://gist.github.com/c7e1ac259e1961ea71de
This means if a newly created translation is deleted right away, the CMS will behave erratically ("Page not found" message instead of readonly form, tree node not marked as deleted).
## Original bug description:

When you delete a page created in foreign language for the translatable module, there are some strange phenomena that can be seen in the following images.
The tests were carried out on a new installation in which the module traslatable is included.
It uses the latest version of SilverStripe 3.1 and translatable module (11/05/2013):
https://github.com/silverstripe/silverstripe-cms/tree/3.1
https://github.com/silverstripe/sapphire/tree/3.1
https://github.com/silverstripe/silverstripe-translatable
![transdeleted01](https://f.cloud.github.com/assets/1523607/492725/3bee6b56-bae3-11e2-9ff7-f9f7804263f4.png)
![transdeleted02](https://f.cloud.github.com/assets/1523607/492727/4073d472-bae3-11e2-9c99-41144ce648d2.png)
![transdeleted03](https://f.cloud.github.com/assets/1523607/492728/4418c9ac-bae3-11e2-9ff5-44d49ffe6d72.png)
![transdeleted04](https://f.cloud.github.com/assets/1523607/492729/47fc8784-bae3-11e2-8236-23f5d420ec8d.png)
![transdeleted05](https://f.cloud.github.com/assets/1523607/492731/4df08bf4-bae3-11e2-8384-c8ff269afe51.png)
![transdeleted06](https://f.cloud.github.com/assets/1523607/492732/54a13296-bae3-11e2-88fb-ad881bb4b8e2.png)
![transdeleted07](https://f.cloud.github.com/assets/1523607/492733/58b63f34-bae3-11e2-945c-ab0ffa170d3a.png)
![transdeleted08](https://f.cloud.github.com/assets/1523607/492734/5da65e2a-bae3-11e2-941c-1a047a841c6e.png)

Regards,
Jose A.

**Comment by robbieaverill** [comment]
Can't reproduce any longer on SS 1.5.x or higher. If this is still a problem for anybody please feel free to reopen.
