### ISSUE TITLE
Allow translation of many_many relationships

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-translatable#12]
Related to http://open.silverstripe.org/ticket/6668

Basically add an extra "Locale" column on the join table, and ensure queries are filtered by this property.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
