### ISSUE TITLE
Assets don't working

### ISSUE THREAD

**Issue by feingestalten** [silverstripe/silverstripe-translatable#135]
Creating new folders, moving files, entering folders doesn't work with Translatable…

Every Action puts '?locale=de_DE' at the end of URL. If you remove this from URL it will work, but every click adds '?locale=de_DE' again to the URL and brake Assets from working… Also tested with clean SS 3.0.5 and Translatable 1.0…

**Comment by robbieaverill** [comment]
Please feel free to reopen this issue if you're still experiencing it in the latest versions of translatable.
