### ISSUE TITLE
Error on 'Delete draft' for translated pages

### ISSUE THREAD

**Issue by Martimiz** [silverstripe/silverstripe-translatable#136]
SS3.1-dev + Translatable master dd 03-09-2013

Deleting translated draft pages results in an errror in updateTreeNodes because the ids parameter is empty. Every once in a while it does actually work - but I haven't been able to find out why/when exactly.
- create a new translation
- on the new page do More options -> Delete draft 

![delete-draft-isssue-20130903](https://f.cloud.github.com/assets/614243/1073180/183a8992-14a2-11e3-9953-7385a9077db0.png)

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
