### ISSUE TITLE
Improved version of Translatable::choose_site_locale with setlocale() and HTTP_USER_AGENT detection

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-translatable#14]
Migrated from http://open.silverstripe.org/ticket/5122, see for patch file and further comments.

I've created an improved version of Translatable::choose_site_locale with session support, browser language detection and member locale detection. Locale will be assigned in order with following priority:

?Locale= URL
--2. "Locale" Session--

Member->Locale
Browser detection

**Comment by robbieaverill** [comment]
@chillu feel free to reopen if you want to. There's not enough detail here to go by and the old link is dead.
