### ISSUE TITLE
Language dropdown in Pages section listview

### ISSUE THREAD

**Issue by Martimiz** [silverstripe/silverstripe-translatable#141]
SilverStripe 3.1 & Translatable master  dd 6-9-2013

This is not a bug - but shouldn't there be a language dropdown in the Listview tab of the Pages section as well?

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
