### ISSUE TITLE
Creating a new page on a sitetree which isnt the default locale adds faulty DB records.

### ISSUE THREAD

**Issue by hubertusanton** [silverstripe/silverstripe-translatable#156]
The following bug occurs after updating Translatable to the latest version: 
When creating a new page under another on a language (right click) which is not the default, the page is created in the DB under the right parentID but is using the default locale. This results in the page being gone after reloading the backend.

Think this is caused by the changing of Locale to locale in TranslatableCMSMainExtension.php
on line 156 

```
function updateLinkPageAdd(&$link) {
	$locale = $this->owner->Locale ? $this->owner->Locale : Translatable::get_current_locale();
	if($locale) $link = Controller::join_links($link, '?locale=' . $locale);
}
```
with Locale (translation added in nl_NL ok)

http://localhost/trtest/admin/pages/add/AddForm/?locale=nl_NL&Locale=nl_NL&action_doAdd=1&ParentID=6&PageType=Page&SecurityID=0a45efd7b7a64ceb7ffd56415ac99ee56828b3b2

with locale (translation not added in nl_NL but record created with wrong (default) locale on en_US )

http://localhost/trtest/admin/pages/add/AddForm/?locale=nl_NL&action_doAdd=1&ParentID=6&PageType=Page&SecurityID=0a45efd7b7a64ceb7ffd56415ac99ee56828b3b2

missing Locale (uppercase) in url so this is obviously used somewhere.
and this is in SS cms/code/controllers/CMSPageAddController.php at line 155

```
if(class_exists('Translatable') && $record->hasExtension('Translatable') && isset($data['Locale'])) {
	$record->Locale = $data['Locale'];
}
```

solving this might be in the cms or in translatable/code/controller/TranslatableCMSMainExtension.php
line 102

```
function updatePageOptions(&$fields) {
	$fields->push(new HiddenField("Locale", 'Locale', Translatable::get_current_locale()));
}
```

Not sure the solution is to just leave the variable starting in uppercase in my project in TranslatableCMSMainExtension.php on line 156, this might break something else? Will look into another solution later, hope someone knows the solution to this.

**Comment by jyrkij** [comment]
Hmm. I noticed this just now. I thought it had been working before but this issue suggests that it has been broken for a long time... What should be done?

**Comment by chillu** [comment]
Can't reproduce with translatable 2.0.x-dev on SilverStripe 3.1.12: http://screencast.com/t/zLnW5Gjl. @jyrkij @hubertusanton Can you provide more details please?

**Comment by hubertusanton** [comment]
Tested this on 3.1.12 and translatable 2.0.6. It still occurs.

I do the following steps (in your video you create pages on root, maybe thats the reason it works?)
The steps below are in a situation where all sites have pages.

1 - log into cms ( you end up in default lang tree )
2 - select another language
3 - create a page under another one (with right click)
4 - publish this page
5 - goto /admin/pages
6 - select 'not default language' the page above in step 3 was created in
7 - the page is not there, because it was created as a faulty record in the wrong language

This causes the bug:
https://github.com/silverstripe/silverstripe-translatable/commit/d194b50b942791467d4e53442bfa9dca144ba95d

When you change ?locale= to ?Locale= which i do in all our projects by hand, its fixed.

**Comment by chillu** [comment]
@hubertusanton Does this PR fix your issue? https://github.com/silverstripe/silverstripe-translatable/pull/193

**Comment by hubertusanton** [comment]
@chillu Yes it does! Thanks! 
Applied your pull request with a patch to 2.0.6 and the problem is solved.
