### ISSUE TITLE
static get_by_locale doesn't make sense

### ISSUE THREAD

**Issue by dio5** [silverstripe/silverstripe-translatable#157]
I may be wrong, but I'm failing to see how static function get_by_locale() can work as is using the new ORM?

```
static function get_by_locale($class, $locale, $filter = '', $sort = '', $join = "", $limit = "") {
        if($locale && !i18n::validate_locale($locale)) {
            throw new InvalidArgumentException(sprintf('Invalid locale "%s"', $locale));
        }

        $oldLang = self::get_current_locale();
        self::set_current_locale($locale);
        $result = $class::get();
        if($filter) $result = $result->where($filter);
        if($sort) $result = $result->sort($sort);
        if($join) $result = $result->leftJoin($join);
        if($limit) $result = $result->limit($limit);
        self::set_current_locale($oldLang);

        return $result;
    }

```

Given that the query only happens once you loop through the results, you'll always end up with a result-set of the 'oldLang'... ?

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
