### ISSUE TITLE
Language Switcher in Pages section does not work on Chrome browser

### ISSUE THREAD

**Issue by dljoseph** [silverstripe/silverstripe-translatable#158]
If you switch from your current language to another language via the drop down, it will immediately refresh back to the current language afterwards.  Works fine in Firefox browser, but fails in Chrome.

**Comment by purplespider** [comment]
Yep, this does indeed appear to be be fixed by https://github.com/silverstripe/silverstripe-framework/pull/3709

For me it didn't work both ways, both to/from translation.

**Comment by dhensby** [comment]
Ok, closing as fixed by https://github.com/silverstripe/silverstripe-framework/pull/3709
