### ISSUE TITLE
To know the page type in _config.php

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-translatable#17]
Migrated to http://open.silverstripe.org/ticket/7058

There should be a standard way of knowing that a page is multilingual by itself, ie Security/Login?, that's to say, that all your texts are translated into global $lang . A function, perhaps in Translatable module, we should give this information, since it should be accessible even from _config.php

We need to know that a page is multi-language by herself to properly connect the locale.

The following, that it is the standard according to documentation, is not suitable for these pages:

Public function init () {

Parent::Init ();

If (Translatable)) { ($this dataRecord hasExtension

i18n::Set locale ($this dataRecord Locale); }

Furthermore, the locale must be possible to change from _config.php, so we should know if a page is multilingual at the time.

We should also have another function to tell us if the page has been created hardcoded.

To know if a page is multilingual by itself, we also suggest that language selection options should be put on the page ($Translations).

Regards, Jose

**Comment by robbieaverill** [comment]
Closing as this is unclear. Feel free to reopen if still relevant.
