### ISSUE TITLE
Redirect breaks PJAX

### ISSUE THREAD

**Issue by mmichelli** [silverstripe/silverstripe-translatable#176]
This redirect breaks the PJAX 

https://github.com/silverstripe/silverstripe-translatable/blob/7342850139c0db36c22baa33b218c430b41ac33f/code/controller/TranslatableCMSMainExtension.php#L42

**Comment by robbieaverill** [comment]
I'm going to close due to inactivity. Please feel free to reopen if you're still experiencing this issue, and provide the version of translatable and SS core that you're using.
