### ISSUE TITLE
URLSegment does not automatically update for new pages

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-translatable#180]
When you create a new page and fill in the "Page name", moving away from the field will automatically update the "Navigation label" and "URL Segment" to match. 

Unfortunately the URL Segment one only seems to work in English. It must be that the update only occurs when the URL Segment is still equal to exactly `"new-$pagename"`, and so it does not update when it's `"neue-$pagename"` or `"nouvelle-$pagename"`.

**Comment by chillu** [comment]
Fixed through core in https://github.com/silverstripe/silverstripe-cms/pull/1168

**Comment by JorisDebonnet** [comment]
Yup, that fixes it, thanks.
