### ISSUE TITLE
It is NOT possible to create and save simple multilingual Page - and here is why + a temp. solution

### ISSUE THREAD

**Issue by codingbq** [silverstripe/silverstripe-translatable#188]
# Reason:

The class **LanguageDropdownField** (in \translatable\code\forms\LanguageDropdownField.php) doesn't have a proper validator nor the parent class **GroupedDropdownField** (in \framework\forms\GroupedDropdownField.php) but the parent class **DropdownField** has a validator method. 

The problem with this mentioned validator method is that it doesn't take care of recursive keys in it - so it doesn't matter which values are set to be valid nor which you select / submit because it will never find a valid entry.

# Note:
> Someone should add a validator to the dropdown field. 

# Temporary solution:

1 . create these two folders in your root:

> myroot\utils\\_config
> myroot\utils\code\forms\

2 . create the file '**LanguageDropboxFieldExt.php**' (in '**myroot\utils\code\forms**') with the content:

```php
<?php

/**
 * An extension to add a proper validator for translable language dropdown field.
 *
 * @package translatable
 */
class LanguageDropdownFieldExt extends DataExtension 
{
    /**
     * Validate this field
     *
     * @param Validator $validator
     * @return bool
     */
    public function validate(Validator $validator)
    {
        $source = $this->getSourceAsArray();
        
        // Patch - Begin
        $iterator = new RecursiveIteratorIterator(new RecursiveArrayIterator($source));
        $keys = array();

        foreach ($iterator as $key => $value) {
            $keys[] = $key;
        }

        // if (!array_key_exists($this->value, $source)) {
        if (!in_array($this->value, $keys)) {
        // Patch - End            
            if ($this->getHasEmptyDefault() && !$this->value) {
                return true;
            }

            $validator->validationError(
                $this->name,
                _t(
                    'DropdownField.SOURCE_VALIDATION',
                    "Please select a value within the list provided X. {value} is not a valid option",
                    array('value' => $this->value)
                ),
                "validation"
            );
            return false;
        }
        return true;
    }
}
```
3 . Create a file called for e.g. '**extension.xml**' (in '**myroot\utils\\_config**') with the content:

```yml
---
Name: translation-extension
After:
  - 'translatable/*'
---
LanguageDropdownField:
  extensions:
    - LanguageDropdownFieldExt
```

4 . Run /dev/build/ 

5 . Enjoy!

**Comment by chillu** [comment]
See #179
