### ISSUE TITLE
Default locale per user

### ISSUE THREAD

**Issue by coreyworrell** [silverstripe/silverstripe-translatable#189]
Hello, is there a way to set a default locale for a user? For instance, my site will have translators, each translator will be assigned to a group for their language (ie: Groups = Translators > Spanish). When that user logs in, it would be great if they only were able to see pages in their language. Or some way to see published English (default locale) pages that they could then create their own locale versions of.

Thank you for your help.

**Comment by chillu** [comment]
I've added some docs around this in 94945a49cd20986603468dc4b4a8c8fd28daf3b7

**Comment by coreyworrell** [comment]
@chillu Great, thank you. What about setting a default locale for users? Right now logging in as a Spanish Translator for example, takes me to the Pages in the English locale because English is my default language. But certain groups/users should be able to have a default locale so they don't have to filter the language every time right?

**Comment by chillu** [comment]
Oh right, completely forgot about the first part of your question :) I would suggest creating a `DefaultLocaleCMSMainExtension` similar to https://github.com/silverstripe/silverstripe-translatable/blob/master/code/controller/TranslatableCMSMainExtension.php#L11. You can use the Config system to ensure it is applied AFTER the `TranslatableCMSMainExtension`, and then check `Member::currentMember()` in an `init()` method. You could either reuse the existing `Member.Locale` property, or (more likely) create a `DefaultLocaleMemberExtension` which adds a new `TranslatableLocale` property to members. In that case, you'll also want to make it editable by adding a dropdown field through `DefaultLocaleMemberExtension->updateCMSFields()`. 

Sorry if that's a bit brief in terms of explanation, maybe ask on the silverstripe.org forums if you need help with the implementation?

**Comment by coreyworrell** [comment]
Thanks @chillu 

That got me a good start. I was having trouble though only setting the user's locale on the first page load so that they can still later filter to other languages if they like.

So I created a `DefaultLocaleCMSMainExtension` class with an `init()` method, and then my **_config/extensions.yml** looks like the following:

~~~yaml
---
Name: ba-extensions
---
SiteConfig:
  extensions:
    - WorkflowApplicable

Member:
  extensions:
    - DefaultLocaleMemberDataExtension
---
Before:
  - translatable/*
---
CMSMain:
  extensions:
    - DefaultLocaleCMSMainExtension
~~~

But my `DefaultLocaleCMSMainExtension` isn't being called before the `TranslatableCMSMainExtension` is being called. The `Before:` statement doesn't seem to do anything. Am I doing something incorrect?

I was going to set the default locale to the users' locale if they were different before Translatable intercepts the request, that way they would be redirected to the new default locale, but also be able to filter to other locales as well.

Thanks for your help!

**Comment by chillu** [comment]
You could try the named rule?

```
Before: 
  - #translatable-extensions
```

The path setting isn't documented on http://docs.silverstripe.org/en/developer_guides/configuration/configuration/, and I haven't used it enough to know how it works, sorry.

**Comment by coreyworrell** [comment]
@chillu I've already tried the name rule, that didn't work either. The path setting is the first bullet point after here: http://docs.silverstripe.org/en/developer_guides/configuration/configuration/#configuration-yaml-syntax-and-rules
