### ISSUE TITLE
Allow complete translation of an existing language or a subtree

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-translatable#19]
Migrated from http://open.silverstripe.org/ticket/4033

On the "Create Translation" tab, add a checkbox to optionally include all children pages when translating into a new language. Make sure all created translations are not published. If any of the children in the tree have been translated already, make sure to honor this translation and don't create a new translation for it.

Ideally, this would work as well when selecting the root-node of a page, so trigger a translation of all toplevel pages including all their children. Currently we don't have a tabbed editform for the root-node, although there might be other use cases for site-wide settings requiring an edit form.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
