### ISSUE TITLE
Problem switching between pages in admin

### ISSUE THREAD

**Issue by andreaslindahl** [silverstripe/silverstripe-translatable#191]
Since installing the translatable module, the admin area has started to behave a little strange. Sometimes when I try to navigate between pages using the site tree nothing happens. The request is made and the URL is updated, but the interface is never updated with the form for the selected page. I have to manually reload the page.

**Comment by dhensby** [comment]
I've heard this bug being experienced regardless of translatable - did you upgrade the framework at the same time?

**Comment by chillu** [comment]
Vague bug report, no feedback for a week - closing off for now. Andreas, feel free to reopen with more details on used SilverStripe and module version, browser, ideally XHR network communication from Chrome Developer Tools etc.

**Comment by dhensby** [comment]
this is bug report I've had:

> User said (in chrome) that if they left the page for a prolonged period (about 10 mins) then came back, the cms would be unresponsive (nothing happened when trying to navigate) and a full reload was required.

Wilfred reported:

> Got a CMS issue - clicking on anything after pageload changes nothing but the url in the address bar. Occasionally it results in a blank page. Refresh takes me where I want to go. this is a pretty much fresh cwp-basic-recipe install

Matt peel (possibly unrelated):

> I've seen that on a side-project I was looking at. I haven't fixed it yet, but it seems to be related to large ModelAdmins in my case (so a ModelAdmin managing 5+ models, each with hundreds of fields)

**Comment by chillu** [comment]
So now we have four vague bug reports. Can you confirm these are all using translatable? Only Wilfred's one indicates that CWP is installed (meaning translatable is active). What leads you to the conclusion that this issue is related to the translatable module?

**Comment by dhensby** [comment]
hmmm - good point. the first bug report came from demo.silverstripe - does that have translatable?

**Comment by chillu** [comment]
Not according to https://github.com/silverstripe/demo.silverstripe.org/blob/master/composer.json

**Comment by dhensby** [comment]
*shuts down the convo*

**Comment by uniun** [comment]
Hi,

I have the same issue with some of my projects. Non of them have translatable installed.

I noticed that after request, that does not change the interface, something tries to load lib.js file. And I don't understand why. It should already loaded.

![network](https://cloud.githubusercontent.com/assets/2812754/11062560/814f78d0-87b8-11e5-9945-1c48506a0caa.png)

**Comment by uniun** [comment]
Also, I have the same project installed on different server only in Dev mode. Everything is OK there.

**Comment by dhensby** [comment]
I believe this bug has been fixed in framework now.

It was caused when someone triggered a flush in another tab and then used the CMS, which caused the CMS to try to load JS files again and everything borked

**Comment by uniun** [comment]
#4553? It looks like that it was reverted.
Now I wonder what may trigger flush (I'm sure that nobody did it with `?flush`).
Anyway this is the wrong place to continue this conversation about that issue :)

**Comment by dhensby** [comment]
Hm I'm not sure it was reverted, what makes you think so?

**Comment by uniun** [comment]
https://github.com/silverstripe/silverstripe-framework/pull/4732

**Comment by dhensby** [comment]
Thanks, I'll investigate

**Comment by tractorcow** [comment]
I've posted there. :) Sorry but the solution in the case of https://github.com/silverstripe/silverstripe-framework/pull/4732 was wrong.
