### ISSUE TITLE
Unable to create translations when logged into group

### ISSUE THREAD

**Issue by mspacemedia** [silverstripe/silverstripe-translatable#195]
Following the example in the documents for creating a group of editors that can translate from the default locale to their 'group' permission language (german) - it is impossible to achieve.

If the editor logs in and the default language is greyed out switching to the translation tab results in no option to create a translation from that page.

If the editor logs in and the default language is not greyed out then they can create a translation but can also edit the default locale which isn't always wanted. 

Ideally, it should be possible to have groups of editors that can view the default locale and then create translations from that content. Currently in 2.0.8 with SS3.1.13 it appears impossible to setup.

**Comment by camfindlay** [comment]
The docs you are referring to are those at https://github.com/silverstripe/silverstripe-translatable/blob/master/docs/en/index.md#user-permissions (From our IRC discussion).

**Comment by camfindlay** [comment]
@mspacemedia  you also mentioned this functionality had worked in previous versions of this module. Can you investigate the previous version and link to the code here for discussion and further regression analysis?

**Comment by mspacemedia** [comment]
Hi Cam,

Just been stepping through the site code in SS3/TR2.0.8 and the Language dropdown field is getting populated with the locales that don't have translations, as is the form action for 'Create Translation'. But when the CMS page is then displayed the canEdit property appears to override the ability to then create the translation as the member from the group doesn't have edit capabilities on the untranslated page itself. Thus it removes the Form Actions and the language dropdown, replacing the dropdown with the text (none).
![screen shot 2015-07-14 at 11 03 48](https://cloud.githubusercontent.com/assets/858675/8670843/3328e996-2a18-11e5-8d72-725e155413ab.png)

The updateCMSFields code is doing it's job - but to me the Permissions is breaking the system at the moment.

I will continue to look through the code base to try and find the offending code itself.

Regards,

Mark

**Comment by robbieaverill** [comment]
Hi @mspacemedia - is this still a problem for you in more recent versions? Feel free to reopen it if it is, but I'm going to close it for now since this issue has been inactive for two years.
