### ISSUE TITLE
Advance workflow module and translatable module

### ISSUE THREAD

**Issue by surf9** [silverstripe/silverstripe-translatable#197]
Hi

Regarding the following issue:

https://github.com/silverstripe-australia/advancedworkflow/issues/225

When publishing an English page with a translated content. Is it normal behaviour to manually publish each translated page even after a successful English content publish via the workflow or does it happen automatically to publish both the English and translated content?

Please let me know.

Thanks.

**Comment by robbieaverill** [comment]
@surf9 I'm going to close this primarily because it's stale, but also because it seems like a question rather than a bug report. Feel free to reopen if you're still having problems!
