### ISSUE TITLE
SS3.2 and Translatable error

### ISSUE THREAD

**Issue by esstonia** [silverstripe/silverstripe-translatable#198]
![no-button](https://github-cloud.s3.amazonaws.com/assets/1775207/10564994/43f94060-75cf-11e5-98eb-c9d099f7b26d.png) cant see the translation create button

**Comment by tractorcow** [comment]
We'll look at fixing this in the upcoming 2.1.0 release

**Comment by lienajp** [comment]
As a workaround, you can use the old version of framework/forms/InlineFormAction.php or replace
		return DBField::create_field(
			'HTMLText',
			FormField::create('input', array(
				'name' => sprintf('action_%s', $this->getName()),
		        'value' => $this->title,
		        'id' => $this->ID(),
		        'class' => sprintf('action%s', $this->extraClass),
			))
		);

by

		return "<input type=\"submit\" name=\"action_{$this->name}\" value=\"{$this->title}\" id=\"{$this->id()}\""
			. " class=\"action{$this->extraClass}\" />";

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-framework/pull/4715 . :D

**Comment by chillu** [comment]
Confirmed the framework fix also fixed the translatable action

**Comment by lienajp** [comment]
thx to all!
greetings from Belgium.

On 28-okt.-2015, at 23:27, Ingo Schommer <notifications@github.com> wrote:

Closed #198 <https://github.com/silverstripe/silverstripe-translatable/issues/198>.
