### ISSUE TITLE
Add Translatabe support in StaticPublisher

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-translatable#20]
Migrated from http://open.silverstripe.org/ticket/4236

StaticPublisher? does not find translated urls when running dev/buildcache.

**Comment by wernerkrauss** [comment]
It does. You have to run buildcache once for each language... Maybe create another task that recreates all pages in all locales at once?

**Comment by chillu** [comment]
@wernerkrauss Good news! You mean `dev/tasks/RebuildStaticCacheTask Locale=de` or something? This would require the `Locale` parameter to be picked up by custom logic though, and have the current Translatable language set before any other queries are fired. Maybe you can document that on https://github.com/silverstripe-labs/silverstripe-staticpublisher/blob/master/docs/en/StaticPublisher.md?

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
