### ISSUE TITLE
Allow switching of language in ModelAdmin

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-translatable#21]
Migrated from http://open.silverstripe.org/ticket/3698

Currently you can't edit records in other languages outside of the main CMS interface, although its generally possible to decorate Translatable onto DataObject? subclasses (not only SiteTree? subclasses). It seems fairly simple to implement:

Add a configuration option which is disabled by default, e.g. ModelAdmin::$use_i18n
Add field to default search forms to choose language - would have an "all languages" option
Add "language" column to result list
A dropdown above the search/create forms would handle the "current language", which influence the default seetings for the language search option, as well as the defaults for "create" action

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
