### ISSUE TITLE
"Insert Link" has no Language dropdown in SS 3.2

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-translatable#214]
The "Insert Link" dialog in the CMS does not show the "Language" dropdown above the "Pages" selector anymore, using Translatable 2.1.x-dev on SS 3.2.1 (also with 2.1.0 on 3.2.0). If I downgrade to 2.0.9 on SS 3.1.16, it DOES show the "Language" dropdown again. 

What could be causing this? I guess it's somewhere in `TranslatableCMSMainExtension`?.. 

A client of mine just discovered this issue and it embarrasses me a bit that I can't fix it (without undoing my somewhat costly 3.1 => 3.2 upgrade) :s

**Comment by JorisDebonnet** [comment]
Can anyone duplicate this issue please?

**Comment by tractorcow** [comment]
Does the issue resolve itself when you upgrade to 3.2.1? I have a feeling it's due to a known issue that was resolved in that version.

**Comment by JorisDebonnet** [comment]
3.2.1 is what I was using. I just tried with 3.2.x-dev (using composer, both framework and cms), but that does not make a difference (Translatable is already using 2.1.x-dev). The languages appear everywhere they should, except in the Insert Link dialog.

**Comment by tractorcow** [comment]
Oh, darn, so not an easy fix as I'd hoped. :)

**Comment by flxlabs** [comment]
I think that will do it: #222

**Comment by JorisDebonnet** [comment]
Excellent, that fixes it indeed!

**Comment by JorisDebonnet** [comment]
Could this fix be merged into 2.1 though? I see that it only made its way into master.

**Comment by dhensby** [comment]
done

**Comment by jyrkij** [comment]
Has this made its way to a released (tagged) version?

**Comment by dhensby** [comment]
I'm afraid not - I was about to tag a fix but I can see a non-semver addition has been made and so that needs to be reverted...

What I'll probably do is merge 2.1 -> 2 and then release a 2.2 version. but I can't do it right now...
