### ISSUE TITLE
With translation enabled creating new child page results in new copy of original parent

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-translatable#22]
Migrated from http://open.silverstripe.org/ticket/4070

Selecting a suitable parent page and using 'Create -> Page -> Go' results in the new page appearing in the site tree root. Refreshing the CMS shows that the new page is actually a child of an unpublished copy of the original parent.

NB: This appears to only happen in the default language. The translation gives the expected result, i.e. the child appears under the parent.

See more discussion on original ticket.

**Comment by robbieaverill** [comment]
Can't reproduce on SS 3.6.0, feel free to reopen if this is still affecting anyone in more recent versions of SS
