### ISSUE TITLE
FEATURE: ability to bulk translate pages

### ISSUE THREAD

**Issue by christopherdarling** [silverstripe/silverstripe-translatable#221]
At the moment when creating a new language of a site it's quite a long-winded process to go through each page and create the relevant translation for it which switches to the new translation each time and then have to go back to the original language and repeat for additional pages. It would be good if there were a way to select multiple pages and mark them all to be translated, perhaps using 'bulk actions'?

**Comment by tractorcow** [comment]
Or you could just use https://github.com/tractorcow/silverstripe-fluent, and not have to manage each site tree independently. ;)

**Comment by thezenmonkey** [comment]
I have a rough working solution. It will bulk translate, but doesn't switch to the target language. I used this module as a guide  [Batch Actions Plus](https://github.com/adrexia/silverstripe-batch-actions-plus)

You need these two classes:

https://gist.github.com/thezenmonkey/36f1f6892efc08969712d68d3c5240f0
https://gist.github.com/thezenmonkey/24e869ca1c5c6d92ebf604dc86d02fd9

You also need this Javascript file
https://gist.github.com/thezenmonkey/de4c0fc1d9549a0f729bb00d3d8cccdd

Once you add those files add the following lines to your _config.php This will add the batch action, hide the LeftAndMail Panel for the Transalte controller and add a Javascript hook

```php
if (!defined('MYSITE_DIR')) {
    define('MYSITE_DIR', rtrim(basename(dirname(__FILE__))));
}

Config::inst()->update('LeftAndMain', 'extra_requirements_javascript', array(MYSITE_DIR.'/javascript/LeftAndMain.TranslateTo.js'));

CMSBatchActionHandler::register('translateto', 'CMSBatchActions_TranslateTo');
CMSMenu::remove_menu_item('CMSBatchAction_TransalteToController');
```

**Comment by tractorcow** [comment]
Thanks for that suggestion @thezenmonkey .

Since this is a feature and it doesn't seem like anyone is planning on taking ownership of this, I'm going to close this ticket.
