### ISSUE TITLE
Versioned translated objects in ModelAdmin

### ISSUE THREAD

**Issue by Sanderha** [silverstripe/silverstripe-translatable#225]
Hi

Im trying to manage ProductPages in ModelAdmin. A ProductPage extends Page, which extends SiteTree. 
To manage versioning in the modeladmin, im using this module: 
https://github.com/Little-Giant/silverstripe-catalogmanager

I found out Translatable didnt work in ModelAdmin, so I used this fix to be able to create translations through ModelAdmin:
https://github.com/silverstripe/silverstripe-translatable/issues/55#issuecomment-66888090

This fix seems to create the translated page in the SiteTree_Live table, instead of the SiteTree table, which obviously gives some issues. **Any idea why this happens?**

Also, I have no idea how to switch Locale when using Translatable in the ModelAdmin, the only way being to directly edit the Locale GET variable in the URL.

Thanks

**Comment by tractorcow** [comment]
you need to put Versioned::reading_stage('Stage') in your modeladmin subclass, I'm afraid. Versioned ModelAdmin does not write to stage by default.

Fixed in 3 branch with https://github.com/silverstripe/silverstripe-framework/pull/5008

**Comment by Sanderha** [comment]
Thanks alot! I'm pretty sure you just saved me a major headache
