### ISSUE TITLE
Filter is removing current Locale on ModelAdmin

### ISSUE THREAD

**Issue by sanderha** [silverstripe/silverstripe-translatable#226]
Sorry if this should really be a SilverStripe issue, I'm not sure.

I have set up a LanguageDropdownField on a ModelAdmin, to switch between locales, because i manage translated objects in a ModelAdmin. The dropdownfield in itself works fine. 
When I try to use the filter functionality on the ModelAdmin, the GET variable "Locale" is removed from the URL, which causes the filter to return results for the default locale.

Any ideas?

**Comment by tractorcow** [comment]
You could add some bootstrapping to the init method of your modeladmin. If the locale param is given, store it in a session. If it's not, check to see if a session variable exists, then Translatable::set_current_locale() from that session variable.

It's not perfect, but it'll prevent requests within the same controller changing locales.

**Comment by sanderha** [comment]
Thanks for the response! The project this issue related was on standby, so I just got back to it.

Your fix works perfectly :)
