### ISSUE TITLE
BUG fix documentation links in readme.md and in docs/

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-translatable#228]
Reference: https://github.com/silverstripe/silverstripe-translatable/issues/227
- readme.md is hard-coded to the master-branch documentation via an absolute link; https://github.com/silverstripe/silverstripe-translatable/blob/master/docs/en/index.md. This should be a relative link so that it points to the correct docs for the current branch. (docs/en/index.md).
- docs/en/index.md has lots of broken links to docs.silverstripe.org, and other places.

This will need to be fixed across all current supported branches (likely 2.0, 2.1, master).

**Comment by tractorcow** [comment]
broken links:
- https://github.com/silverstripe/silverstripe-translatable/blob/master/docs/en/i18n
- http://www.silverstripe.org/Language-Chooser-Widget/
- http://doc.silverstripe.com/doku.php?id=i18n#the_t_function
- https://github.com/silverstripe/silverstripe-translatable/blob/master/topics/translation#setting_the_i18n_locale
- http://translate.silverstripe.org/
- http://silverstripe.org/translatablemodeladmin-module/

**Comment by maxime-rainville** [comment]
Looks like this got fixed by https://github.com/silverstripe/silverstripe-translatable/pull/275
