### ISSUE TITLE
BUG Translatable prevents History-revert

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-translatable#229]
1. Create a page on a site with at least 2 supported locales
2. Do not translate it, so it exists only on 1 language version
3. Make and save a bunch of changes
4. Revert to a previous version (via History tab)

That will fail. It will switch to the History > Translations tab, which says:
> Create new translation
> New language: (none)
> **Please select a value within the list provided. is not a valid option**

**Comment by tractorcow** [comment]
Which exact versions of framework and translatable are you using? I know we've addressed this in at least one release.

**Comment by JorisDebonnet** [comment]
Well, I'm confused... I can not recreate this issue anymore, with Translatable 2.1.1 and either CMS 3.3.1 or 3.2.3. I'll have to pay close attention next time I encounter the issue...

**Comment by tractorcow** [comment]
I think we've fixed it then. :D
