### ISSUE TITLE
Login form not aware of locale

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-translatable#23]
Migrated from http://open.silverstripe.org/ticket/4261

Login form (used with /admin or through the Forum module) is presented in the default language, appending ?locale=xx_XX to /admin does not work (as expected), but it works with /Security/login.

It's maybe that the function I'm using to switch languages is faulty, but it works with all other pages.

**Comment by hohl** [comment]
Any solution to work around this?

**Comment by robbieaverill** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
