### ISSUE TITLE
CMSEditLink doesn't link to the correct locale

### ISSUE THREAD

**Issue by micmania1** [silverstripe/silverstripe-translatable#230]
See https://github.com/silverstripe/silverstripe-lumberjack/pull/32 for reference

**Comment by micmania1** [comment]
Fixes here:
Translatable: https://github.com/silverstripe/silverstripe-translatable/pull/231
CMS: https://github.com/silverstripe/silverstripe-cms/pull/1411

This doesn't fix the CMS edit link, but removes the need to change the link.

**Comment by tractorcow** [comment]
Is this fixed now? :P

**Comment by micmania1** [comment]
Yep. Thanks :+1:
