### ISSUE TITLE
Mention "original page name" in mouse-over in SiteTree

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-translatable#234]
If you're working with Russian, Chinese, Arabic translations etc, it's not easy to figure out which page is which again. Say you need to make a change on the Contact page, but you can't find it in the SiteTree because it's all in a language you don't understand at all. 

There is of course a workaround, and that's by going to the English version of the page, and then going through there to its translation. But that's a bit cumbersome, especially if you need to do changes on multiple pages on the Chinese version. 

So my suggestion is to add the original page name in the mouseover, which currently shows "(Page type: ...) Page Name". 

(It would actually be even more awesome if that standard tooltip could be replaced by a JS-one that supports newlines, then it can be made more clear, but I'm not sure whether a library for such tooltips is already present)

**Comment by tractorcow** [comment]
It's a good idea, but it's a feature request, so please don't be offended if I close this ticket. :)

**Comment by JorisDebonnet** [comment]
Ah, I thought small, specific feature requests could go here as well. Should they go on UserVoice?

**Comment by tractorcow** [comment]
Technically that's the correct place, although small changes are best implemented yourself, since it's unlikely to get picked up by anyone who dosn't need it themselves.

I don't deny it's a good idea though.

**Comment by dhensby** [comment]
@JorisDebonnet if you open a PR, even a broken one, then that'll probably be allowed ;)

**Comment by JorisDebonnet** [comment]
But I was lazy and wanted someone else to do it! :p Anyway, thanks for the suggestion :)
