### ISSUE TITLE
cacheKeyComponent used when locale filter is disabled

### ISSUE THREAD

**Issue by webtorque7** [silverstripe/silverstripe-translatable#239]
Should cacheKeyComponent still return something if filtering is disabled?

I have a case where a get_one is done with the locale filter on. ModelAsController is then failing to lookup the correct page because this result has been cached, even though ModelAsController disables the Translatable filter as the cache keys are the same.

**Comment by tractorcow** [comment]
I think you're right... it should cache on some kind of "disabled-translatable" key if not filtering by a locale.

**Comment by tractorcow** [comment]
Fixed with https://github.com/silverstripe/silverstripe-translatable/pull/240
