### ISSUE TITLE
Translations of sub-pages only visible if parent page is translated

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-translatable#24]
Migrated from http://open.silverstripe.org/ticket/5388

In the backend i'm using pages which are not visible on the frontend to structure my content. These pages have sub-pages which are visible in the frontend. That works pretty well.

Example structure:

```
+-- Site Content
  +-- 2010                    (invisible, en_EN)
    +-- 03                    (invisible, en_EN)
      +-- Article 1           (visible, de_DE, en_EN)
      +-- Article 2           (visible, de_DE, en_EN)
    +-- 04                    (invisible, en_EN)
      +-- Article 1           (visible, de_DE, en_EN)
      +-- Article 2           (visible, de_DE, en_EN)
```

These 'parent' pages (2010, 03, 04) are in the default language (english) If i now translate a sub-page to another language (german/french/etc.) they are not reachable in the frontend. I have to do a translation of the invisible parent-page to see the translated sub-page in the frontend as well.

Both the parent-pages and it's sub-pages are of a custom type derived from the default "Page" type.

Is there something I forgot to do?

I enabled translation using Object::add_extension('SiteTree?', 'Translatable'); in the mysite/_config.php I also tried to enable translation not globally but only in my derived page type for the sub-pages but that didn't work as well.

**Comment by jallen0927** [comment]
+ 1

**Comment by jallen0927** [comment]
+1

**Comment by tractorcow** [comment]
Fixed with installing https://github.com/tractorcow/silverstripe-fluent.

**Comment by robbieaverill** [comment]
Closing as this is how translatable is supposed to work (in that it has a separate SiteTree essentially per locale). Users who want this behaviour should investigate Fluent as mentioned above.
