### ISSUE TITLE
Widget vs. Translatable in 3.3 and 3.2

### ISSUE THREAD

**Issue by innomedia** [silverstripe/silverstripe-translatable#242]
When extending Widget and WidgetArea with Translatable. Filtering the Widget works in most cases. But when trying to add widgets translatable seems to add a tab named "Translatable" to the widget which the widget is not cabable of:

`user_error(FieldList::addFieldToTab() Tried to add a tab to object 'FieldList' - 'Root' didn't exist.,256)
FieldList.php:303

FieldList->findOrMakeTab(Root.Translations,Translations)
Translatable.php:1070

Translatable->updateCMSFields(FieldList,,,,,,)
Object.php:978

Object->extend(updateCMSFields,FieldList)
Widget.php:28`

**Comment by innomedia** [comment]
Apparently this happens when getCMSFields() in a custom widget is extendable:
$this->extend('updateCMSFields', $fields);

**Comment by dhensby** [comment]
I think it's because in 3.1 we stopped using 'Root.x' for tab names and in 3.2 we probably removed the backwards compatibility of that?

**Comment by innomedia** [comment]
This probably breaks the widgetareaeditor on translated pages when a pagetype uses 
`$this->extend('updateCMSFields', $fields);` 
too

**Comment by tractorcow** [comment]
Would changing `Translatable::updateCMSFields` to check if the $fields has tabs fix this issue? Instead of adding the new fields to a tab, it could instead add them to a fieldgroup, couldn't it?

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
