### ISSUE TITLE
Dutch root website "page not found" if the English HomePage is unpublished

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-translatable#247]
I have not found the exact cause of this yet, but here is my situation: 
- Default language is set to nl_NL (both Translatable and i18n). 
- SiteTree with ID 1 is the Dutch homepage, which I have called "thuispagina". It loads when you go to mydomain.com/
- There's an English translation of this homepage that I have called "home", so people need to go to mydomain.com/home to see the English version. 

That works fine as long as both pages are published. But if I unpublish the English page, also the Dutch one shows "Page not found" when not logged in. It works when I go to mydomain.com/thuispagina, but not when I go to mydomain.com/. 

It is especially sneaky because it DOES still work as long as you are logged in to the CMS (which I always am), so you have to wait until your customer tells you that the whole website seems to have stopped working ...

After testing a bit, I see that this also happens when I "Archive" the English homepage, so I do wonder how I'd ever get it back to work if I did that on production and wouldn't be able to retrieve the English page to publish it again!

I don't get this issue when I unpublish another translation, only when I unpublish the English one.

I am working with SS 3.4 and Translatable 2.2.0.

**Comment by tractorcow** [comment]
It's not, for whatever reason, sneakily unpublishing the dutch home page at the same time is it? It definitely has a record in SiteTree_Live for the dutch home?

**Comment by tractorcow** [comment]
can you see what link is being returned by RootURLController::get_homepage_link() on requests that fail in this way? I.e. what url does this controller THINK is the home page? I can see there is some custom Translatable logic in there that may need updating.

**Comment by JorisDebonnet** [comment]
I've just tried RootURLController::get_homepage_link(), and it returns "home". That's while neither SiteTree nor SiteTree_Live contain any records with URLSegment='home'. SiteTree_versions does, both on the Dutch and the English website, but that shouldn't matter right? 

My _config.php has: 
```php
Translatable::set_default_locale('nl_NL');
i18n::set_locale('nl_NL');
```
So I'd expect it to try find a homepage somewhere on the Dutch version. 

Perhaps it has something to do with `Translatable::get_homepage_link_by_locale`? When I var_dump & die in there, I see that `$original` is `false`. This section is no doubt the problem: 
```php
self::set_current_locale(self::default_locale());
		$original = SiteTree::get_by_link(RootURLController::config()->default_homepage_link);
```
If I understand correctly, it's trying to find a SiteTree object with URLSegment "home" (default_homepage_link), but that doesn't exist anywhere. 

I can 'solve' the issue by adding this to my _config.php: 
```php
RootURLController::config()->default_homepage_link = 'thuispagina';
```

I realise I have created an edge case though, by renaming my default homepage to something other than "home", and then using "home" for a 'translation' (into English) from my default language.

**Comment by lohe** [comment]
Hei,
Actually that is very true and problematic. If you want to create separated templates for first page, default page and any other page type, then you need to start with so called homepage/firstpage template, not the default Page. Therefore - IF to change default language from English to some other language AND draft the home page for English language, hole site goes down as page not found. Not sure why is that like that, but if there is a workaround - even better :)

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
