### ISSUE TITLE
Pressing "return" on a CMS page creates a translation

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/silverstripe-translatable#251]
- I have a home page in English, no translations yet. 
- I change its Title and press return. 
- If anything, I'd expect it to just save the draft or something -- but instead, Translatable kicks in and creates a new translation with the top listed language. It did not even save my new Title, it only created the Translation. 

Clearly, the "return" action executes the form on the "Translations" tab, which is not expected. I believe something should be built in to prevent the "New translation" from being submitted, unless the button on that tab is explicitly clicked.

**Comment by dhensby** [comment]
This will be the browser following the behaviour of submitting the form with the first submit button it finds. Not sure of the actual solution but one would be to pull the translation action out so it's not the first action in the DOM or make it a link instead of a button.

**Comment by dhensby** [comment]
It would break user expectation IMO.

I think enter should be save as draft almost always.

**Comment by JorisDebonnet** [comment]
Agreed. So I suppose I should raise this on the cms repository instead? Or is this framework?..

**Comment by dhensby** [comment]
I'm say framework as it's an issue with "admin"

**Comment by robbieaverill** [comment]
The InlineFormAction we're using in the 3.x compatible version is removed in 4.x, so we'll need to replace that anyway

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
