### ISSUE TITLE
Silverstripe Blocks

### ISSUE THREAD

**Issue by hohl** [silverstripe/silverstripe-translatable#255]
I'm using this plugin in combination with the [Silverstripe Blocks]() plugin. Blocks are data objects so they should be translated automatically. If I create a block on my primary locale anything works fine. However, if I create a block for a second locale, the created block gets assigned the primary local. (If I manually change the locale to the secondary language everything is fine and I even can modify the block via the CMS.)

Any ideas how I could fix that? I though data objects are automatically translated?

**Comment by hohl** [comment]
I found out, that in the create form HTML the field `Locale` is always set to the primary locale. Independent of what the `?Locale=` used to show the form. Any ideas, I'd really need to get that working.

**Comment by thezenmonkey** [comment]
It seems to be a problem with addTranslatableFields. When creating a new DataObject via a Gridfield Detail Form the Locale of the Parent Object isn't passed to the new DataObject.

The first call to addTranslatableFields contains the parent Page obejct with the correct Locale, the second call is on the new DataObject, which has it's Locale set back to default.

**Comment by thezenmonkey** [comment]
@hohl see this pull request for a fix [PR#256 ](https://github.com/silverstripe/silverstripe-translatable/pull/256)

**Comment by hohl** [comment]
Wow, thank you very much for your quick response and even a push request. I'll give it a try!

**Comment by hohl** [comment]
Wow, that fixed it. Thank you very much!
