### ISSUE TITLE
Unable to translate inside templates

### ISSUE THREAD

**Issue by Sommereder** [silverstripe/silverstripe-translatable#257]
I translated the pages from within the backend into multiple languages. No problem. But I cannot translate from within the templates. It always uses the en.yml file, even though es.yml exists and holds the correct data. The regular syntax "<%t ... %>" is used and $ContentLocale shows the right language (eg. es-ES). My SilverStripe version is 3.5.1 and translatable is at 2.2.

Is this a bug or am I missing something? Thanks.

Best, Mario

**Comment by bilekt3** [comment]
I have realized same behavior, I have to set i18n locale manually, then it works.

**Comment by robbieaverill** [comment]
Hi @MarioHofer - thanks for reporting. Would you be able to provide a more specific set of steps to reproduce, or even a failing unit test demonstrating the problem?

**Comment by 3Dgoo** [comment]
I had the same problem, but I had not abled the _t() function in templates as described in the documentation:
https://github.com/silverstripe/silverstripe-translatable/blob/2.2/docs/en/index.md#enabling-the-_t-function-in-templates

Following those instructions solved my problem.

Is this the same problem that you were having @Sommereder ? If so, does this solve the problem (I know this is from 2 years ago). If so, perhaps we can close this issue.

**Comment by robbieaverill** [comment]
I'm happy to assume that your assessment is correct for now, we can always reopen if necessary =) Thanks
