### ISSUE TITLE
Existing translations show links to translations regardless of canView permissions

### ISSUE THREAD

**Issue by micahsheets** [silverstripe/silverstripe-translatable#261]
I have some users that are only allowed to edit specific translations. However in the Existing translations sections of the Translations tab does not check canView. Also Create new translation does not check canCreate.

**Comment by robbieaverill** [comment]
@micahsheets could you please provide your framework and translatable versions?

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
