### ISSUE TITLE
Failed build on 4.0.1, installed through composer

### ISSUE THREAD

**Issue by rohitbanerjee** [silverstripe/silverstripe-translatable#269]
Module failed build right after composer installation, on SS 4.0.1 on windows 10 xampp localhost server. Gave error "Class "Extension" not found ..... "

`composer require silverstripe/translatable dev-master`

**Comment by dhensby** [comment]
4.x support hasn't been added to this module yet.

**Comment by robbieaverill** [comment]
See #263 and #264 for progress
