### ISSUE TITLE
Describe session-based language switching in docs

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-translatable#27]
Migrated from http://open.silverstripe.org/ticket/7044

Followup from #7041

The "Switching languages" section mentions the ?locale= GET param, and using that param would only show links to pages in a certain language. But some pages are statically linked, e.g. Security/login. Describe how to work around this by using session based locales through init(). Also fix usage of Translatable::set_reading_locale().

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
