### ISSUE TITLE
Problem using Insert Link > Page on the site

### ISSUE THREAD

**Issue by thaissa** [silverstripe/silverstripe-translatable#272]
I'm not sure if that's a problem with Translatable module, TreeDropdownField, or both.

When using translatable pages, and opening the Insert Link inside a HTML Editor, the TreeDropdownField doesn't reload with the correct Locale, when chosing the Locale from the field right above it.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
