### ISSUE TITLE
PHP Fatal error:  Class 'Extension' not found in ./translatable/code/controller/TranslatableCMSMainExtension.php on line 5

### ISSUE THREAD

**Issue by alfredoyong** [silverstripe/silverstripe-translatable#274]
After installing translatable using composer 

`composer require silverstripe/translatable dev-master`

got this fatal error in php log. When  Any ideas? 

`PHP Fatal error:  Class 'Extension' not found in ./translatable/code/controller/TranslatableCMSMainExtension.php on line 5`

**Comment by robbieaverill** [comment]
Can you please provide the versions of SS CMS and Translatable you’re using?

**Comment by alfredoyong** [comment]
Yes! thanks for answering.
 Im using:
`silverstripe/framework             4.0.0              The SilverStripe framework
silverstripe/cms                   4.0.0              The SilverStripe Content Management System
silverstripe/translatable          dev-master 9012ab7 Allows translation of DataObject and SiteTree records into multiple languages`

I was able to move forward in  this issue by adding "use" statements at the beginning of the module php files, like adding these lines in translatable/code/model/Translatable.php:
`<?php
use  SilverStripe\ORM\DataExtension;
use SilverStripe\Security\PermissionProvider;
use SilverStripe\Forms\FormTransformation;
`
BUT, I have now a lot of warnings, and when clicking to edit the "important" pages, I receive an "Internal Server Error". Looking at the ajax call initiated by the CMS, I got these answer from server: 

`Warning] Declaration of Translatable::augmentSQL(SQLSelect $query, ?DataQuery $dataQuery = NULL) should be compatible with SilverStripe\ORM\DataExtension::augmentSQL(SilverStripe\ORM\Queries\SQLSelect $query, ?SilverStripe\ORM\DataQuery $dataQuery = NULL)
GET /admin/pages/edit/show/2
Line 159 in /Applications/MAMP/htdocs/nobu400/translatable/code/model/Translatable.php`

**Comment by robbieaverill** [comment]
Ok thanks. This module is not compatible with SilverStripe 4. We suggest you try using tractorcow/silverstripe-fluent instead.

**Comment by robbieaverill** [comment]
For reference, SS4 compatibility work in progress is at #264. If anyone wants to pick it up they’d be welcome to

**Comment by thaissa** [comment]
If this module isn't compatible with SS4, then it should not say it is: https://addons.silverstripe.org/add-ons/silverstripe/translatable
