### ISSUE TITLE
Proposal for translation tool

### ISSUE THREAD

**Issue by ilyaspiridonov** [silverstripe/silverstripe-translatable#285]
Please consider using [GitLocalize](https://gitlocalize.com) to manage translations.
It's free and syncs with GitHub.

**Comment by maxime-rainville** [comment]
Thanks for the suggestions. This module targets Silverstripe 3 which is currently in limited support. 

[Silverstripe 4 uses transifex to manage localisation data](https://docs.silverstripe.org/en/4/contributing/translations/#the-online-translation-tool). We're heavily invested in Transifex right now, so we would need a pretty strong case for adopting a different solution.

If there's a specific problem you're encountering, maybe create an RFC on the [framework](https://github.com/silverstripe/silverstripe-framework/issues/new) repo and provide more details.
