### ISSUE TITLE
Translatable: "Global"/"Untranslatable" properties

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-translatable#3]
Migrated from http://open.silverstripe.org/ticket/3722

Currently you only have "full" translations in our Translatable datamodel, meaning every single column is copied and editable for a specific language. This will lead to problems for properties like prices or foreign key relations - you have to rely on the translator/editor to keep the records consistent across languages.
## Master/Original? Record

First problem: In our current datamodel we don't have the notion of a specific "original" - every record is essentially a "translation" in a pool of related pages. This was necessary to avoid requiring that each translated tree is a subset of a master tree (meaning if your "default language" is english, you can't have a german page which is not hooked into an english original). We define "original" as "record in default language" (a static property on Translatable class). This might not always exist, though...
## Column Selection

Developers need some way to denote which properties are translatable or global.
### Blacklisting

All columns _except_ from the specified ones are translatable.
### Whitelisting

Columns need to be explicitly marked as translatable. This gives a more finegrained control, especially when dealing with additional columns from decorators and modules.
### Solution 1: Self Joins

Translatable->augmentSQL() would self-join all required tables for a specific dataobject with themselves. This has to happen automatically on a very low level (SQLQuery), meaning we have to detect certain SQL-patterns by string-parsing to limit usage and make sure we still produce valid SQL. As this happens on a database level, its fairly performant though.

To research: Can you self join specific columns only?
### Solution 2: ORM-level fallbacks

Each DataObject? would have an optional reference to an "original" or "fallback" record, which is queried upon construction time. This record would be stored as a DataObject? itself, with some special flag to denote its fallback-status. The fallback can just be in one language (Translatable::default_lang()) - if the record doesn't have a related record in this language, there is no fallback for it. Each call to __get() and __set() would now determine if the field in question is translatable, and set the record accordingly. Each call to DataObject::write() would essentially cause two writes (record and fallback).

The big downside of this approach is that its very hard to side-step the ORM and get fallback from straight SQL (see "Solution 1: Self Joins").

How do dynamic getters influence the fallback mechanism?

Does DataObject? caching still work in the same way when each DataObject? can have a fallback?

If no fallback exists, do we allow editing of all fields on the "translation"? Otherwise these fields will not be writeable from anywhere...What happens if this fallback is created later on, after all fields have been written to the translation?
## Misc
- Interesting article for different database approaches:  http://www.gsdesign.ro/blog/multilanguage-database-design-approach/
- Symfony/Propel? split all i18n columns into a separate table:  http://vit.free.fr/symfony/0.6.3/i18n.html ("Text information in the database")

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
