### ISSUE TITLE
In CMS, DataObject Popup in Translated Page thinks it is default locale.

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-translatable#30]
From http://open.silverstripe.org/ticket/6433

( Code at: http://open.silverstripe.org/attachment/ticket/6433/mysite.zip )

I added Translatable extension to SiteTree and a DataObject, 'DOStaffMember'. Using a default locale of en_US, i translated a page to another language, and when i open a DataObject from a ComplexTableField, the popup believes it is an en_US locale, not the current locale. this is running silverstripe 2.4.5 release codebase.

**Comment by robbieaverill** [comment]
Feel free to reopen if this still affects anyone using SS 3.5/3.6 or newer but I'm closing since this is reported against SS 2.x
