### ISSUE TITLE
Translatable SiteConfig edit translations

### ISSUE THREAD

**Issue by ghost** [silverstripe/silverstripe-translatable#46]
We are unable to view or edit the different translations of the SiteConfig object using the cms. On the translations tab the different translations are not loaded. Is there a quick fix? 

We are currently using it by appending ?locale=en_US so that we can edit the english translation of our SiteConfig.

Thank you in advance!

**Comment by shlinx** [comment]
@chillu I'm currently still see this issue that @customies mentioned. I'm using silverstripe@3.5 and translatable@2.2.0
