### ISSUE TITLE
Allow "original" fields on translated DataObjects via Translatable->updateCMSFields()

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-translatable#5]
Migrated from http://open.silverstripe.org/ticket/4231, see patch and comments there.

Currently all the updatecmsfields logic is limited to SiteTree? objects, and it makes certain assumptions on the controller context by the "create translation" action.

I've attached a patch that shows a language dropdown for DataObjects? instead, which sets the locale explicitly rather than through a hidden field. There is no "create translation" action at the moment.

Creating translations is essentially a controller task, and hence shouldn't be baked in to Translatable. It works for CMSMain, now we have to get it working for ComplexTableField? (#4199), ModelAdmin? (#3698) etc.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
