### ISSUE TITLE
Remove Translatable references from core and create extension points

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-translatable#54]
While the bulk of the logic has been separated out into this module,
there are still many places across SilverStripe CMS which this modules relies on:
- CMSBatchActionHandler->handleAction()
- ContentController->handleRequest()
- ContentController->ContentLocale()
- ErrorPage::response_for()
- LeftAndMain->init()
- ModelAsController->getNestedController()
- RootURLController::get_homepage_link()
- SearchForm
- SiteConfig
- SiteTree->RelativeLink()
- SiteTree->getSiteConfig()

These APIs mostly require either hooks for an Extension subclass,
or refactoring to allow better customization.

**Comment by robbieaverill** [comment]
Commenting for the sake of highlighting this as an important change for the core modules in future. Perhaps we could migrate this issue to a repo that it won't be forgotten on?

**Comment by chillu** [comment]
Good point, I've moved this to https://github.com/silverstripe/silverstripe-framework/issues/7317

**Comment by altwohill** [comment]
Note that I will be removing the references to `Translateable` as part of https://github.com/silverstripe/silverstripe-cms/issues/2401
I note the master build of this module is failing anyway, so we're not going to make things worse
