### ISSUE TITLE
Creating translations in GridField/ModelAdmin doesn't work

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-translatable#55]
Migrated from http://open.silverstripe.org/ticket/7771

I added a DataObject? and ModelAdmin? with this code:

```
class Category extends DataObject {
        static $db = array(
                'Title' => 'Varchar(255)'
        );
}

class CategoryAdmin extends ModelAdmin {
        public static $url_segment = 'categories';
        public static $menu_title = 'Categories';
        public static $managed_models = array('Category');
}
```

and this in the mysite/_config.php:

`Object::add_extension('Category', 'Translatable');`

I then created a Category and attempted to make a new translation of it, and nothing happened. I didn't see any Javascript errors either.

**Comment by damian-coobers** [comment]
Releated #196

**Comment by damian-coobers** [comment]
@axyr Your solution is working, but if your item, selected from GridView has also GridView, items within have the same problem. Do you know a solution?

**Comment by damian-coobers** [comment]
@chillu Have you found working solution? Is there one?

**Comment by Sanderha** [comment]
@axyr Your solution works to a certain extend. However, I try to manage Pages in modeladmin. When using your solution, it creates a translation of the page in the SiteTree_Live table, and not in the SiteTree table. 
Any ideas?

**Comment by andy2708** [comment]
I can't seem to get your solution working @axyr.
Has there been a proper fix implemented for this yet?

I never see anything in the model admin and adding anything debug related to TestObjectAdminDetailForm_ItemRequest methods dont show up as if it never gets hit.
Any help?

**Comment by camelscript** [comment]
Still cant figure this out. At start there was no button when I added the code from axyr, the button apperared. Now the button works, but when i create translation the list under "Existing translations" is empty. 
I debugged so far that i found out that the bug arises at translatable/code/model/Translatable.php:1117
Where method 
`$existingTranslation->hasMethod('CMSEditLink')`
returns false, though `$existingTranslation` has linked translation.

**Comment by maxime-rainville** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
