### ISSUE TITLE
Translatable: Support many_many_extraFields

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-translatable#7]
Migrated from http://open.silverstripe.org/ticket/2793

This would entai creating extra "_lang" tables for each manymany table (e.g. "MembersGroups_lang"), which would just hold the translated information, and the ID to the original row in the manymany table.

For lack of easy definition at the moment, I would suggest for all extrafields to be translatable by default. As a limitation, we could just create the "_lang" tables when extrafields exist.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
