### ISSUE TITLE
The action 'LangForm' does not exist in class CMSPagesController

### ISSUE THREAD

**Issue by mechano** [silverstripe/silverstripe-translatable#72]
Still this error when I select language and presso GO into the admin panel.

Silverstripe 3.0.3rc2
translatable from github 2012-11-23

And The button create when I select the second language, doesn't work.

**Comment by galla-placidia** [comment]
silverstripe LTS 3.1.13
branch translatable 2.0
it doesn't happen anything on clicking "create" 
On selecting the hopefully created language obove the sitetree, the obove Error is thrown.
config: 
Translatable::set_default_locale('en_US');
Object::add_extension('SiteTree', 'Translatable');
Object::add_extension('CarouselPage', 'Translatable');
Object::add_extension('SiteConfig', 'Translatable');
