### ISSUE TITLE
Changing the Page Type makes translations inaccessible (SS3.1.0beta)

### ISSUE THREAD

**Issue by smindel** [silverstripe/silverstripe-translatable#76]
after changing a page type of a page that has translations in the cms, getTranlations doesn't return those translations anymore although they are still linked in the translation group. another problem is that these translations are stuck with the original page type forever because the field in the cms is readonly.

since the page type field for translations in the cms is readonly i assume that the page types of all translations are supposed to be changed to the one of the default translation in the Translatable::onBeforeWrite() method. this seems to be broken.

the query for getTranslations filters by classname so getTranslations only returns translations of the same classname. thats probably why the Translatable::onBeforeWrite() method uses this to work around the filter:

``` php
    $this->owner->ClassName = $changedFields['ClassName']['before'];
    $translations = $this->owner->getTranslations();
    $this->owner->ClassName = $changedFields['ClassName']['after'];
```

the weired thing is that `$changedFields['ClassName']['before'];` is set to the _new_ value instead of the original so getTranslations returns an empty DataList and the following foreach doesn't get executed.

assuming again i think that `$changedFields['ClassName']['before']` equals `$changedFields['ClassName']['after']` may be due to not using DataObject::setClassName() to change the class name but DataObject::newClassInstance($newpagetype) on the default translation so that the _original_ original class name is not available in Translatable::onBeforeWrite() anymore.

i dont't have a patch to supply at the moment. i'm not even sure if this is a problem in translatable, framework or cms.

**Comment by robbieaverill** [comment]
Seems that this is resolved now. Feel free to reopen if not.
