### ISSUE TITLE
Add support for "language subfolders" for pages with Translatable extension

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-translatable#8]
Migrated from http://open.silverstripe.org/ticket/3877

See discussions on  http://groups.google.com/group/silverstripe-dev/browse_thread/thread/17908f7318decfac#

The translatable feature is only half as useful if all pages have to be addressed with their specific locale as a GET parameter, e.g.  http://mydomain.com/mypage/?locale=de_DE.
- While this can be achieved through URL rewriting on Apache level (for a specific language domain or subdomain), it would be more "beginnerfriendly" to allow putting the locale in a toplevel subfolder.
  /de_DE/mypage, /en_US/mypage - this way, the same URLSegment "mypage" could be reused for different languages. This is imposing a URL structure on the system, but seems to be a widespread way of doing things. Would have to be tested for compatibility for the nestedurl work.
- For SEO reasons, a page should just be available under ONE url - so if /de_DE/mypage is the primary location, then /mypage should redirect with a Google-friendly 302 http status code.
- The homepage as a special case should also redirect correctly (mydomain.com -> mydomain.com/<default locale>), without showing the /home suffix.
- SiteTree?->validURLSegment() should be allowed to overwrite built-in uniqueness checks to allow mydomain.com/de/mypage as well as mydomain.com/en/mypage (ideally only voting TRUE if this specific rule is matched, and doesn't interfere with other logic which might disallow a URL segment, e.g. subsites)
- Links in navigation and CMS URL preview should adapt to the new pattern
- Having unique URLs is also important for caching (proxies, browser) as well as static exports - please test this still works with the new implementation.
- Optional: Validate that the approach still works with the subsites module

**Comment by maxime-rainville** [comment]
Unfortunately, [SilverStripe 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for SilverStripe 3 going forward.

You can read the [SilverStripe Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
