### ISSUE TITLE
The selected language changes to the default when I change menu option (SS 3.0.3). 

### ISSUE THREAD

**Issue by Josua2012** [silverstripe/silverstripe-translatable#80]
Hi all!

When I select a language in Pages (eg Spanish) and change to another menu option (eg Files or Settings), when I go back to 'Pages', english is selected again.

Furthermore, I can not edit the Settings content in another language.
Settings is always in the default language.
What I can do?

Regards,
Jose A.

**Comment by robbieaverill** [comment]
>When I select a language in Pages (eg Spanish) and change to another menu option (eg Files or Settings), when I go back to 'Pages', english is selected again.

This is still happening, but I'm not sure whether this is a bug or not. It seems to be acceptable behaviour to me since you're leaving the translated page context and re-entering it again. That being said, I'd say retaining the language would also be OK 😄 

>Furthermore, I can not edit the Settings content in another language. Settings is always in the default language.

Are you talking about the labels and values of a page's settings tab, or the values of free text input fields?

**Comment by dhensby** [comment]
> Are you talking about the labels and values of a page's settings tab, or the values of free text input fields?

I think this is regarding whether SiteConfig has translatable versions (ie: can create translations for different locales). i think this is an issue for the SiteConfig repo and not here.

@robbieaverill are we planning on fixing these issues or shall we close?

**Comment by robbieaverill** [comment]
@dhensby I think leave them open, this module still has active support under CWP

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
