### ISSUE TITLE
Incorrectly fetches locale with the user forms module

### ISSUE THREAD

**Issue by promotion** [silverstripe/silverstripe-translatable#90]
Having installed user-forms and translatable got an error when trying to "Delete all submissions" or "Delete Submission" in "Form Submissions" tab. 

The error says : "Error at line 312 of [DOMAIN]/translatable/code/model/Translatable.php"

Problem is in static function set_current_locale($locale)  function. Debuging $locale variable would show :

``` php
Debug (Translatable::set_current_locale() in Translatable.php:310)
en_US/deletesubmission/?id=2

ERROR [User Error]: Uncaught InvalidArgumentException: Invalid locale "en_US/deletesubmission/?id=2"
IN POST /admin/pages/edit/EditForm/field/Reports?locale=en_US/deletesubmission/?id=2
```

SO it takes locale as 'en_US/deletesubmission/?id=2' . 

I'm not sure if this is your bug , or is this user-defined form bug, so please redirect or answer me if possible

**Comment by robbieaverill** [comment]
@promotion is this issue still affecting you?

**Comment by promotion** [comment]
@robbieaverill - have no idea, its been 3.5 years since then, im not even sure which project was affected :)
