### ISSUE TITLE
Security Groups can't switch language

### ISSUE THREAD

**Issue by riddler7** [silverstripe/silverstripe-translatable#93]
LangForm uses permission VIEW_LANGS but there is nowhere to set this permission. When logged in as an admin there is no problem, but if you want to setup groups to edit individual languages they are unable to switch as the dropdown is readonly.

**Comment by maxime-rainville** [comment]
Unfortunately, [Silverstripe CMS 3 has entered limited support in June 2018](https://www.silverstripe.org/blog/update-on-silverstripe-5-x/). This means we'll only be fixing critical bugs and security issues for Silverstripe CMS 3 going forward.

You can read the [Silverstripe CMS Roadmap](https://www.silverstripe.org/software/roadmap/) for more information on our support commitments.
